"""DND-104 — emit the full per-architecture comparison table (markdown).

Reads the screen from `reliability_mask.py` and writes
`analysis/architecture_table.md` with every field the DND-104 brief requires:
plain-English mechanism, diagram-as-text, actuator count, repeated-cell
complexity, mask-generation method, reset method, full-cycle timing, purchased
BOM estimate, fabrication difficulty, reliability risks, prototype path, and the
decisive falsifier.

Run: python 10-reliability-mask/analysis/make_table.py
"""

from __future__ import annotations

import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))
import reliability_mask as m  # noqa: E402

OUT = HERE / "architecture_table.md"


def row(label: str, values: list[str]) -> str:
    return "| " + label + " | " + " | ".join(values) + " |"


def build() -> str:
    s = m.screen()
    rows = s["ranked_feasible_full"] + s["rejected_full"]
    names = [r["name"].split(" ")[0] for r in rows]      # A1..A7
    lines: list[str] = []
    lines.append("# DND-104 — full per-architecture comparison table")
    lines.append("")
    lines.append("Generated by `analysis/make_table.py`. Evidence class: "
                 "CALCULATION over sourced limits + CAD; no print, purchase or "
                 "measurement (DND-27).")
    lines.append("")
    lines.append("| Field | " + " | ".join(names) + " |")
    lines.append("|---|" + "---|" * len(names))

    def val(fn) -> list[str]:
        return [fn(r) for r in rows]

    lines.append(row("Architecture", val(lambda r: r["name"])))
    lines.append(row("Family", val(lambda r: r["family"])))
    lines.append(row("Plain-English mechanism", val(lambda r: r["one_liner"])))
    lines.append(row("Bought actuators", val(lambda r: str(r["actuators_bought"]))))
    lines.append(row("Column states", val(lambda r: str(r["column_states"]))))
    lines.append(row("Repeated moving parts", val(lambda r: f'{r["reliability"]["repeated_moving_parts"]:,}')))
    lines.append(row("Precision contacts/cell", val(lambda r: str(r["reliability"]["precision_contacts_per_cell"]))))
    lines.append(row("Compliant printed parts", val(lambda r: f'{r["reliability"]["compliant_printed_parts"]:,}')))
    lines.append(row("Wear interfaces", val(lambda r: f'{r["reliability"]["wear_interfaces"]:,}')))
    lines.append(row("**Silent elements (reliability score)**", val(lambda r: f'**{r["reliability"]["silent_elements"]:,}**')))
    lines.append(row("Readback", val(lambda r: "yes" if r["reliability"]["has_readback"] else "no")))
    lines.append(row("Recovery", val(lambda r: r["reliability"]["recovery"])))
    lines.append(row("Mask medium", val(lambda r: r["mask_medium"])))
    lines.append(row("Mask write inside budget", val(lambda r: "yes" if r["mask_write_inside_budget"] else "no (off-line)")))
    lines.append(row("Regional granularity", val(lambda r: r["regional"]["granularity"])))
    lines.append(row("Reset method", val(lambda r: r["regional"]["note"].split(";")[0][:60])))
    lines.append(row("Full-cycle time", val(lambda r: f'{r["timing"]["full_cycle_s"]} s')))
    lines.append(row("Visible transition", val(lambda r: f'{r["timing"]["visible_transition_s"]} s')))
    lines.append(row("< 30 s", val(lambda r: "PASS" if r["clears_30s"] else "FAIL")))
    lines.append(row("Tabletop load (A7)", val(lambda r: "PASS" if r["clears_tabletop_load"] else "FAIL")))
    lines.append(row("Purchased parts", val(lambda r: f'${r["parts_usd"]:.2f}')))
    lines.append(row("Delivered (x1.16)", val(lambda r: f'${r["delivered_usd"]:.2f}')))
    lines.append(row("< $250 parts", val(lambda r: "PASS" if r["clears_parts"] else "FAIL")))
    lines.append(row("Correlated failure", val(lambda r: r["correlated_failure"])))
    lines.append(row("Single-cell failure", val(lambda r: r["single_cell_failure"])))
    lines.append(row("Serviceable", val(lambda r: "yes" if r["serviceable"] else "no")))
    lines.append(row("Prototype path", val(lambda r: r["prototype_coupon"])))
    lines.append(row("Decisive falsifier", val(lambda r: r["decisive_falsifier"])))
    lines.append(row("Docs", val(lambda r: r["docs"])))
    lines.append("")
    lines.append("## Reliability ranking (lower score is better)")
    lines.append("")
    lines.append("| Rank | Architecture | Reliability score | Silent elements | All gates feasible |")
    lines.append("|---:|---|---:|---:|---|")
    ordered = sorted(rows, key=lambda r: r["reliability_score"])
    feasible_names = {r["name"] for r in s["ranked_feasible_full"]}
    for i, r in enumerate(ordered, 1):
        lines.append(f"| {i} | {r['name']} | {r['reliability_score']} | "
                     f"{r['reliability']['silent_elements']:,} | "
                     f"{'YES' if r['name'] in feasible_names else 'no'} |")
    lines.append("")
    lines.append(f"**Selected: {m.SELECTED_NAME}** (the only all-gate-feasible machine).")
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    md = build()
    OUT.write_text(md)
    print(f"wrote {OUT.relative_to(HERE.parent.parent)} ({len(md)} bytes)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
